module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        "logo": "url('@/assets/animals_logo.svg')",
      },
      colors: {
        "info-ultralight": "#ecf5fa",
        "info-light": "#6abae5",
        "info": "#459fd0",
        "info-dark": "#2e6a8b",
        "success-ultralight": "#ebf4e5",
        "success-light": "#66b100",
        "success": "#3c9700",
        "success-dark": "#286400",
        "warning-ultralight": "#fde8e9",
        "warning-light": "#f73c4a",
        "warning": "#ed1c24",
        "warning-dark": "#bd161c",
        "neutral-ultralight": "#f2f3f4",
        "neutral-light": "#e6e6e6",
        "neutral": "#767676",
        "neutral-dark": "#555",
        "zoopoints-ultralight": "#fff4ca",
        "zoopoints-light": "#ffe178",
        "zoopoints": "#ffd647",
        "zoopoints-dark": "#eac33c",
        "stampcard-ultralight": "#fae9ec",
        "stampcard-light": "#ce223d",
        "stampcard": "#b81e37",
        "stampcard-dark": "#a61b32",
        "black": "#000",
        "black-10": "rgb(0 0 0 / 0.1)",
        "black-30": "rgb(0 0 0 / 0.3)",
        "black-70": "rgb(0 0 0 / 0.7)",
        "white": "#fff",
        "white-00": "rgb(255 255 255 / 0)",
        "white-30": "rgb(255 255 255 / 0.3)",
        "white-70": "rgb(255 255 255 / 0.7)",
        "app-bg": "#f2f3f4",
        "brand": "#ffda00",
        "primary-ultralight": "#ebf4e5",
        "primary-light": "#66b100",
        "primary": "#3c9700",
        "primary-dark": "#286400",
        "secondary-ultralight": "#fff0e7",
        "secondary-light": "#f80",
        "secondary": "#ff6200",
        "secondary-dark": "#cc4e00",
        "autoship-ultralight": "#c1deae",
        "autoship-light": "#4c8824",
        "autoship": "#39780f",
        "autoship-dark": "#1f4e01",
        "bonus-ultralight": "#fff4ca",
        "bonus-light": "#ffe178",
        "bonus": "#ffd647",
        "bonus-dark": "#eac33c",
      },
    },
  },
  plugins: [],
};




